CREATE TABLE Employee
(
EMPNO INT not null primary key GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
ENAME varchar(50) NOT NULL,
JOB_TITLE varchar(150) NOT NULL,
ADMISSION_DATE  date NOT NULL
);